source 'https://rubygems.org'

gem 'rails', '~> 3.2.12'
gem 'devise', '~> 2.2.3'
gem 'devise-encryptable'
gem 'haml', '>= 3.2.0.beta.3'
gem 'sass'
gem 'inherited_resources'
gem 'pg'
gem 'rake'
gem 'chef', '>= 0.10.8'
gem 'net-ssh', :require => 'net/ssh'
gem 'net-sftp'
gem 'rails_config'
gem 'site_meta'
gem 'state_machine'
gem 'simple_form', '~> 2.0.1'
gem 'hiredis', '~> 0.4.5'
gem 'redis', require: ["redis/connection/hiredis", "redis"]
gem 'redis-mutex'
gem 'resque', :git => 'https://github.com/defunkt/resque.git', :branch => '1-x-stable'
gem 'resque-lock-timeout'
gem 'whenever', :require => nil
gem 'i18n'
gem 'airbrake'
gem 'centrum_faktur'
gem 'grit'
gem 'default_value_for'
gem 'rfc-822'
gem 'statsd-instrument'
gem 'metrics', :git => "git://github.com/Ragnarson/metrics.git"
gem 'dalli', '>= 2.1.0'
gem 'committed_changes'
gem 'paper_trail', '~> 2'
gem 'kaminari'
gem 'fog', :git => "git://github.com/fog/fog.git"
gem 'monit', '>= 0.2.2'
gem 'cache_method'
gem 'systemu'
gem 'bson_ext'
gem 'mongo'
gem 'chronic'
gem 'mailchimp', '~> 0.0.7.alpha'
gem 'after_commit_queue'
gem 'flipper'
gem 'flipper-redis'
gem 'cache_digests', github: 'rails/cache_digests'
gem 'newrelic-redis'
gem 'rpm_contrib'
gem 'newrelic_rpm'
gem 'dnsimple-ruby', github: 'aetrion/dnsimple-ruby'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
# locked for chef (has ~> 1.1.0 for net-ssh-multi), 1.1.1 and 1.1.2 are yanked
gem 'net-ssh-multi', '1.1.0'
gem 'puma', '~> 2.0.0.b6'
gem 'msgpack'
gem 'rack-cors', require: 'rack/cors'

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass', '~> 2.2'
end

gem 'jquery-rails'
gem 'jquery-ui-rails', github: 'joliss/jquery-ui-rails'

gem 'em-http-request'
